WITH RANKEDCOLONY AS (
    SELECT 
        ID, 
        SIZE_OF_COLONY,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_RANK
    FROM ECOLI_DATA
)

-- 코드를 작성해주세요
SELECT 
    ID,
    CASE 
        WHEN SIZE_RANK = 1 THEN "CRITICAL"
        WHEN SIZE_RANK = 2 THEN "HIGH"
        WHEN SIZE_RANK = 3 THEN "MEDIUM"
        WHEN SIZE_RANK = 4 THEN "LOW"
       END AS COLONY_NAME
FROM RANKEDCOLONY
ORDER BY ID